# Generated by Django 4.0.3 on 2022-03-26 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='teacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('picture', models.URLField()),
                ('comment', models.TextField(max_length=3000)),
                ('education', models.CharField(max_length=255)),
                ('subjects', models.CharField(max_length=255)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isAnonymous', models.BooleanField(default=True)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 - Awful'), (2, '2 - Ok'), (3, '3 - Good'), (4, '4 - Very Good'), (5, '5 - Amazing!')])),
                ('commentReview', models.TextField(blank=True, max_length=3000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacherRater.teacherprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
